### PR TITLE
Update issue templates to new format

### PR DESCRIPTION
**Pull request by Madis0**
Updates the issue templates to new format, adding the template chooser for easier navigation. Did not change the template itself.

See also [Github's documentation](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) or [see how it looks like](https://github.com/Madis0/uBlock-issues/issues/new/choose).

### CODE REVIEW

**Comment by gwarser** [comment]
How it looks: https://github.com/Madis0/uBlock-issues/issues/new/choose

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gwarser** [comment]
@Madis0 undo this last one - it should be moved to original gorhill repo.

**Comment by Madis0** [comment]
Now I made one for the original repo too, but I cannot PR unfortunately.

Diff: https://github.com/gorhill/uBlock/compare/master...Madis0:master
Demo: https://github.com/Madis0/uBlock/issues/new/choose

**Comment by gorhill** [comment]
Cool stuff, thanks for this.

I will look into pulling your changes in uBlock repo, after which this will make you a collaborator and you will then be able to submit PR in the future.

**Comment by gorhill** [comment]
Actually I have removed access restrictions at gorhill/uBlock now that it's unlikely issues will be opened at the wrong place with the new template.

**Pull request merged**
