### PR TITLE
Bug report form

### PR DESCRIPTION
**Pull request by Madis0**
Updates the bug report template to the [new form-based format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

Pros:
* Users are more likely to fill it properly as it is easier to read
* Every required field is actually enforced
* [Different types of form elements](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#keys)

Cons:
* "Currently in beta and subject to change" (but you can always just revert if something goes wrong)
* YAML is a pain to debug
* Couldn't replicate the "prerequisites" section 1:1

[How the creation looks](https://github.com/Madis0/uBlock-issues/issues/new?assignees=&labels=&template=bug_report.yml)

[How the created issue looks](https://github.com/Madis0/uBlock-issues/issues/1)

P.S. Please squash merge 😁

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks :+1:

**Comment by uBlock-user** [comment]
Finally, no more template evading/removed submissions !

**Comment by gorhill** [comment]
In 1.38.5b2, I added a button in the Support pane to report issues to GitHub. I think uBO could craft some URLs to GitHub issue trackers to cause a new issue to be filled with a users' customized settings taken from their own instance of uBO, this would allow to remove many checkboxes from there.

**Comment by Madis0** [comment]
> I thought your opinion is: "That would be just another documentation everyone will ignore." so why denying yourself now.

My point was that adding more text will not make users read it more, so maybe try clarifying the existing text to make it more readable. Though I do not have concrete ideas so perhaps let's leave the discussion at that.

> can an extension (uBO) detect whether user's browser's settings are altered or other extensions are present? Or is it forbidden for security reasons?

Yes, some settings can be detected, for example: https://developer.chrome.com/docs/extensions/reference/privacy/

**Comment by felix-22** [comment]
> Madis0 : My point was

Okay, but making more readable something which already is readable enought, won't make it more readable either...the documentation is very good.

**Comment by uBlock-user** [comment]
> the developers know that the user has not tested on the default settings

The new parameter "Configuration" at the end of template will reveal user's uBO configuration.

**Comment by felix-22** [comment]
So does new "Bug Report From Support Pane", not require testing on uBO with default lists/settings anymore? This will litter the issue tracker with invalid issues, this is the opposite effect we have been trying to acheive isn't it?

**Comment by uBlock-user** [comment]
> So does new "Bug Report From Support Pane", not require testing on uBO with default lists/settings anymore?

Volunteers won't need to ask them verbally, volunteers will read through the "Configuration" settings provided at the end, to realise whether the OP is on default settings or not and if not, volunteers will make a recommendation to the OP accordingly.

**Comment by gorhill** [comment]
I can't remember why I removed it, I will put it back.

**Pull request merged**
